# -*- coding: utf-8 -*-
"""netflix_titles_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUJ5nTWe_OXM7o9yq30FEifriM1J-w9h
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("netflix_titles.csv.zip")

print(data.head())
print(data.info())

sns.countplot(x='type', data=data)
plt.title("Number of Movies vs TV Shows on Netflix")
plt.show()

data['date_added'] = data['date_added'].str.strip()
data['date_added'] = pd.to_datetime(data['date_added'], errors='coerce')

data['year_added'] = data['date_added'].dt.year

year_count = data['year_added'].value_counts().sort_index()

year_count.plot(kind='line', marker='o')
plt.title("Netflix Content Growth Over Years")
plt.show()

country_count = data['country'].value_counts().head(10)

country_count.plot(kind='bar')
plt.title("Top Countries Producing Netflix Content")
plt.show()

genre_count = data['listed_in'].value_counts().head(10)

genre_count.plot(kind='bar')
plt.title("Top Genres on Netflix")
plt.show()